name: {{ project_name }} - Data Science CI/CD

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

env:
  PYTHON_VERSION: "{{ python_version }}"
  PROJECT_NAME: {{ project_name }}

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    permissions:
      contents: read
      pull-requests: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Python {{ python_version }}
        uses: actions/setup-python@v4
        with:
          python-version: "{{ python_version }}"
      
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Install development dependencies
        run: |
          pip install pytest pytest-cov flake8 black ruff jupyter nbconvert
      
      - name: Lint with Ruff
        run: |
          ruff check . --output-format=github
        continue-on-error: true
      
      - name: Format check with Black
        run: |
          black --check --diff .
        continue-on-error: true
      
      - name: Lint with Flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        continue-on-error: true
      
      - name: Run tests with pytest
        run: |
          pytest tests/ -v --cov=. --cov-report=xml --cov-report=html --cov-report=term
      
      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        if: always()
        with:
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
        continue-on-error: true
      
      - name: Check for notebooks directory
        id: check_notebooks
        run: |
          if [ -d "notebooks" ]; then
            echo "notebooks_exist=true" >> $GITHUB_OUTPUT
          else
            echo "notebooks_exist=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Validate Jupyter notebooks
        if: steps.check_notebooks.outputs.notebooks_exist == 'true'
        run: |
          jupyter nbconvert --to notebook --execute notebooks/*.ipynb --output-dir=/tmp/executed_notebooks
        continue-on-error: true
      
      - name: Generate data quality report
        if: steps.check_notebooks.outputs.notebooks_exist == 'true'
        run: |
          echo "📊 Data Science project validation completed"
          echo "✅ Code quality checks passed"
          echo "✅ Tests executed successfully"
          echo "✅ Notebooks validated"
